[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi-responses-api-demo"
version = "0.1.0"
description = "Toy GPT-style backend using FastAPI, SQLite, and OpenAI Responses API."
authors = [{ name = "Vinod M" }]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.111.0,<1.0.0",
    "uvicorn[standard]>=0.30.0,<1.0.0",
    "sqlalchemy>=2.0.30,<3.0.0",
    "pydantic-settings>=2.3.2,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "openai>=1.37.1,<2.0.0",
    "alembic>=1.13.1,<2.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0,<9.0.0",
    "httpx>=0.27.0,<1.0.0",
    "pytest-asyncio>=0.23.7,<1.0.0"
]

[tool.uv]
default-groups = ["dev"]
